name: Test and Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary webdrivermanager
          webdrivermanager firefox --linkpath /usr/local/bin

      - name: Run Robot tests
        id: robot_tests
        run: |
          robot --variable BROWSER:firefox --variable HEADLESS:True tests/ --outputdir results/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4 # Updated from v3
        with:
          name: robot-results
          path: results/

  deploy:
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # Folder containing swag_labs.html
          branch: gh-pages
          clean: true
